In [3]:
import numpy as np

## Basic Array operations 

In [10]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [14]:
# all will be converted to string

arr2= [1,3,4,5,'manthan']
str_arr=np.array(arr2)
print(str_arr)

['1' '3' '4' '5' 'manthan']


In [15]:

l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)
mat= np.array(l)
print(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
## Generating arrays

np.arange(10) # aray from zero to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,100,8) # initial final step

array([ 2, 10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90, 98])

In [20]:
np.zeros([6,8]) # matrix of 6,8

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones([7,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
## linspace
np.linspace(1,10,5) #range from 1 to 10 and total requied points are 5 evenly spaced values will be there

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
## randomly generated functions

In [ ]:
np.random.rand(10) ## from 0 to 1 (normalised)

array([0.63767277, 0.56422427, 0.54888831, 0.3834162 , 0.56750908,
       0.07172727, 0.27926939, 0.10648905, 0.73978733, 0.87961395])

In [ ]:
arr=np.random.randn(100) ## standardize values from -3 to 3
print(arr.max())
print(arr.min())

2.158125808006833
-2.876810802850246


In [31]:
np.random.randint(5,10,100)

array([6, 6, 7, 9, 6, 7, 9, 7, 8, 7, 5, 6, 9, 5, 7, 7, 7, 7, 5, 6, 6, 5,
       7, 8, 8, 9, 8, 6, 8, 5, 5, 5, 7, 7, 8, 5, 6, 7, 9, 7, 6, 5, 9, 9,
       5, 9, 9, 7, 6, 5, 8, 9, 9, 8, 9, 6, 8, 5, 6, 7, 7, 9, 8, 5, 8, 7,
       8, 9, 9, 7, 6, 5, 6, 5, 7, 8, 9, 6, 5, 7, 5, 8, 8, 9, 6, 9, 9, 8,
       9, 9, 5, 5, 6, 8, 6, 9, 7, 9, 5, 8])

## array attributes

In [33]:
arr= np.array([[1,2,3],[6,7,8],[11,2,3]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int64')

## array methods 

In [37]:
arr.max()

np.int64(11)

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.sum()

np.int64(43)

In [ ]:
np.sum(arr,axis=1) ## Row wise Sum

array([ 6, 21, 16])

In [ ]:
np.sum(arr,axis=0)### column wise sum

array([18, 11, 14])

In [42]:
np.sum(arr,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [43]:
arr.mean()

np.float64(4.777777777777778)

In [44]:
arr.std()

np.float64(3.1894889098682944)

In [ ]:
arr.argmax()## index of the max element

np.int64(6)

In [ ]:
arr.argmin() # index of min element

np.int64(0)

In [47]:
#reshape

In [53]:
arr= np.arange(1,31)
arr.reshape(6,5) # the count should match

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [55]:
arr=np.arange(1,10)
arr[1]

np.int64(2)

In [56]:
arr[1:3]

array([2, 3])

In [58]:
arr[4::2]

array([5, 7, 9])

In [4]:
arr= np.arange(1,31).reshape(6,5)

In [ ]:
arr[3:6,3:]  ## slice first row and then column

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
## boolean Indexing and getting only the even number
arr=np.arange(1,11)
bool_index= arr % 2 ==0
arr=arr[bool_index]
print(arr)


[ 2  4  6  8 10]


## Array Operations 